<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Lantern.Functions</RootNamespace>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libs\Lantern.Base\Lantern.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="host.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lantern.Api.Tests" />
    <InternalsVisibleTo Include="Lantern.Functions.Tests" />
  </ItemGroup>

</Project>
