#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: set up signing and the UAT address for the Android build (.github/workflows/android.yml).
# Secrets go to the uat environment (it holds the approval gate), never into the repo.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Kept outside the repo. Back these two files up: a lost key means a new SHA-1 and a Firebase re-registration.
ENV_FILE="$HOME/lantern-secrets/lantern-android.env"
KEYSTORE="$HOME/lantern-secrets/lantern-android-release.keystore"
# The same resource group and app the API pipeline (api.yml) deploys.
RESOURCE_GROUP=rg-lantern-dev
APP=ca-lantern-uat
KEY_ALIAS=lantern

mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")"

# keytool from a throwaway JDK container, so no Java is needed here. The password reaches it by environment.
keytool_docker() {
  docker run --rm --user "$(id -u):$(id -g)" -e STOREPASS \
    -v "$(dirname "$KEYSTORE"):/keys" eclipse-temurin:17-jdk keytool "$@"
}

# set_env_secret NAME VALUE writes a secret on the uat environment.
set_env_secret() {
  if printf '%s' "$2" | gh secret set "$1" --env uat >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$1")
    printf '  %s✓ set%s uat secret %s\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("uat secret $1 (gh secret set $1 --env uat)")
    warn "could not set uat secret $1"
  fi
}

banner "Android build: signing key and UAT address"

stage "Signing key"
if [[ -f "$KEYSTORE" ]]; then
  say "Keeping the existing key. A new one would change the SHA-1 registered in Firebase."
  STOREPASS=$(_existing ANDROID_KEYSTORE_PASSWORD || true)
  [[ -n "$STOREPASS" ]] || { warn "no saved password in $ENV_FILE; restore it or remove the key to start over"; exit 1; }
else
  command -v docker >/dev/null 2>&1 || { warn "docker is needed for keytool"; exit 1; }
  say "Creating a release key (valid about 27 years) in $KEYSTORE"
  STOREPASS=$(openssl rand -hex 24)
  export STOREPASS
  keytool_docker -genkeypair -storetype PKCS12 -keystore "/keys/$(basename "$KEYSTORE")" \
    -alias "$KEY_ALIAS" -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass:env STOREPASS -dname "CN=Lantern, O=Lantern" >/dev/null
  chmod 600 "$KEYSTORE"
fi
export STOREPASS
# A PKCS12 key has the same password as its store.
write_env ANDROID_KEYSTORE_PASSWORD "$STOREPASS"
write_env ANDROID_KEY_PASSWORD "$STOREPASS"
write_env ANDROID_KEY_ALIAS "$KEY_ALIAS"
chmod 600 "$ENV_FILE"
warn "Back up $KEYSTORE and $ENV_FILE (a password manager is fine). Nothing else holds them."
pause

stage "Signing SHA-1 for Firebase"
say "Register these fingerprints with the Android app in Firebase when you do the sign-in story (#105):"
keytool_docker -list -v -keystore "/keys/$(basename "$KEYSTORE")" -alias "$KEY_ALIAS" -storepass:env STOREPASS \
  | grep -E 'SHA(1|256):' | sed 's/^ */  /'
pause

stage "UAT address"
command -v az >/dev/null 2>&1 || { warn "az is needed to read the deployed app's address"; exit 1; }
fqdn=$(az containerapp show -g "$RESOURCE_GROUP" -n "$APP" --query properties.configuration.ingress.fqdn -o tsv)
[[ -n "$fqdn" ]] || { warn "could not read the address of $APP"; exit 1; }
LANTERN_API_URL="https://$fqdn"
say "Read the address of $APP (${fqdn:0:12}…, not shown in full)."

stage "GitHub uat environment secrets"
say "Writes 5 secrets on the uat environment of this repository: the key, its password and alias, and the UAT address."
confirm "Set them now?" || { warn "stopped before writing secrets"; exit 1; }
command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 || { warn "gh is not signed in"; exit 1; }
set_env_secret ANDROID_KEYSTORE_BASE64 "$(base64 -w0 "$KEYSTORE")"
set_env_secret ANDROID_KEYSTORE_PASSWORD "$STOREPASS"
set_env_secret ANDROID_KEY_ALIAS "$KEY_ALIAS"
set_env_secret ANDROID_KEY_PASSWORD "$STOREPASS"
set_env_secret LANTERN_API_URL "$LANTERN_API_URL"

finish
note "Next: GitHub → Actions → Android - Check and Build → Run workflow, approve the uat deployment, then download the APK."
printf '\n'
